{% set name = "django-easy-logging" %}
{% set version = "0.60" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-easy-logging-{{ version }}.tar.gz
  sha256: e48d539b42f1ecf5653b7e594c35efb0a08fd11256cd507a7f8f8eb83cabb698

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pdm-pep517
    - pip
  run:
    - python >=3.7
    - loguru >=0.6.0

test:
  imports:
    - dj_easy_log
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/neutron-sync/django-easy-logging
  summary: Easy Django logging with Loguru
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - millsks
